### ISSUE TITLE
SASL does not work

### ISSUE THREAD

**Issue by txtsd** [Throne3d/node-irc#95]
I've been trying to connect via SASL to libera, esper and rizon.

It just fails every time with
```
home/txtsd/git/proj/node_modules/irc/lib/irc.js:849
                        throw err;
                        ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  prefix: 'irc.rizon.no',
  server: 'irc.rizon.no',
  command: 'err_notregistered',
  rawCommand: '451',
  commandType: 'error',
  args: [ 'projBot', 'You have not registered' ]
})
    at new NodeError (node:internal/errors:363:5)
    at Client.emit (node:events:354:17)
    at Client.<anonymous> (/home/txtsd/git/proj/node_modules/irc/lib/irc.js:643:26)
    at Client.emit (node:events:365:28)
    at iterator (/home/txtsd/git/proj/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (<anonymous>)
    at TLSSocket.handleData (/home/txtsd/git/proj/node_modules/irc/lib/irc.js:841:15)
    at TLSSocket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:285:11) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    prefix: 'irc.rizon.no',
    server: 'irc.rizon.no',
    command: 'err_notregistered',
    rawCommand: '451',
    commandType: 'error',
    args: [ 'projBot', 'You have not registered' ]
  }
}
```
The accounts that are trying to login were manually registered and tested with sasl in weechat.

**Comment by txtsd** [comment]
I was actually not using irc-upd.
